### ISSUE TITLE
Add instructions in README.md about SignalProtocolStore, directory and makeKeyId( )

### ISSUE THREAD

**Issue by andresribeiro** [privacyresearchgroup/libsignal-protocol-typescript#62]
There is no instructions in README.md on how/ from where we should import the `SignalProtocolStore`, `directory` and also the `makeKeyId( )` function

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1182658981846409/1198944761209890)

**Comment by rolfeschmidt** [comment]
Yes, this needs to be clarified. If you want quick answers you can look at [this demo app](https://github.com/privacyresearchgroup/libsignal-typescript-demo) to see the SDK in use in a simple React app. The demo app is deployed [here](https://signal-demo.privacyresearch.io/).

In then end, each of these are things a developer will need to implement themselves:
* You can cut and paste the `SignalProtocolStore` from the [test directory](https://github.com/privacyresearchgroup/libsignal-protocol-typescript/blob/master/src/__test__/storage-type.ts) to get started, but this is not intended for production use. Your implementation will depend on your application: a React Native store will look different from a web one; you may want to use local storage, server storage, or a hybrid; you need to decide how you'll test whether an identity key really binds to an identity.
* `directory` also has a simple in-memory implementation [in the demo app](https://github.com/privacyresearchgroup/libsignal-typescript-demo/blob/master/src/signal-directory.ts). In reality, this will probably be a layer over some simple API calls. Again, it is up to you: given a user address, how will you find a prekey bundle? 
* `makeKeyId()` can be any function that generates unique identifiers.

All of these are important - and probably deserve good reference implementations - but are not part of the protocol. The README should make this more clear.
