### ISSUE TITLE
Flipped `EncryptionResultMessageType` enum

### ISSUE THREAD

**Issue by park-jemin** [privacyresearchgroup/libsignal-protocol-typescript#81]
Was looking into deeper TypeScript integration with my project, and found this odd bit of code:
https://github.com/privacyresearchgroup/libsignal-protocol-typescript/blob/a4dd273e060c4131e1a7385adf92f367392ffaf5/src/session-types.ts#L55-L58

Given that the implementations currently use this, should this be flipped?
https://github.com/privacyresearchgroup/libsignal-protocol-typescript/blob/a4dd273e060c4131e1a7385adf92f367392ffaf5/README.md?plain=1#L235-L247

I can also open a PR for this!

**Comment by Joepd1** [comment]
What did you do?

**Comment by rolfeschmidt** [comment]
Fixed by #82
